package org.example.expensestrack.Model;


import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "expenses")
public class Expense {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // The Backend's Primary Key

    @Column(unique = true, nullable = false)
    private String localId; // The UUID generated by your Android app while offline

    private BigDecimal amount;
    private String description;
    private LocalDateTime expenseDate;

    // Default constructor required by JPA
    public Expense() {}

    // Constructor for creating new instances
    public Expense(String localId, BigDecimal amount, String description, LocalDateTime expenseDate) {
        this.localId = localId;
        this.amount = amount;
        this.description = description;
        this.expenseDate = expenseDate;
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getLocalId() { return localId; }
    public void setLocalId(String localId) { this.localId = localId; }
    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public LocalDateTime getExpenseDate() { return expenseDate; }
    public void setExpenseDate(LocalDateTime expenseDate) { this.expenseDate = expenseDate; }
}
